#additional EDA Script
par(mfrow=c(3,3))

plot(CEPICorNumbers, xaxt="n", pch=19,col="blue", ylim=c(-1, 1), main="Monthly Change in Export Price Index", xlab = "", ylab="Correlation")
axis(1, labels = Names2, at=1:2, las=2, col="blue")
plot(SICorNumbers, xaxt="n", pch=19,col="blue", ylim=c(-1, 1), main="Monthly Satisfaction Index - Govt Based", xlab = "", ylab="Correlation")
axis(1, labels = Names2, at=1:2, las=2, col="blue")
plot(TempCorNumbers, xaxt="n", pch=19,col="blue", ylim=c(-1, 1), main="Average Monthly Temperature", xlab = "", ylab="Correlation")
axis(1, labels = Names2, at=1:2, las=2, col="blue")
plot(BirthCorNumbers, xaxt="n", pch=19,col="blue", ylim=c(-1, 1), main="Average Monthly Births", xlab = "", ylab="Correlation")
axis(1, labels = Names2, at=1:2, las=2, col="blue")
plot(SIECorNumbers, xaxt="n", pch=19,col="blue", ylim=c(-1, 1), main="Monthly Satisfaction Index - External", xlab = "", ylab="Correlation")
axis(1, labels = Names2, at=1:2, las=2, col="blue")
plot(ExpCorNumbers, xaxt="n", pch=19,col="blue", ylim=c(-1, 1), main="Yearly Exports", xlab = "", ylab="Correlation")
axis(1, labels = Names2, at=1:2, las=2, col="blue")
plot(GloCorNumbers, xaxt="n", pch=19,col="blue", ylim=c(-1, 1), main="Yrly # of Globalisation Party Members", xlab = "", ylab="Correlation")
axis(1, labels = Names2, at=1:2, las=2, col="blue")
plot(AEPICorNumbers, xaxt="n", pch=19,col="blue", ylim=c(-1, 1), main="Average Monthly Export Price Index", xlab = "", ylab="Correlation")
axis(1, labels = Names2, at=1:2, las=2, col="blue")
plot(PPICorNumbers, xaxt="n", pch=19,col="blue", ylim=c(-1, 1), main="Monthly Producer Price Index", xlab = "", ylab="Correlation")
axis(1, labels = Names2, at=1:2, las=2, col="blue")
plot(NatCorNumbers, xaxt="n", pch=19,col="blue", ylim=c(-1, 1), main="National Holidays", xlab = "", ylab="Correlation")
axis(1, labels = Names2, at=1:2, las=2, col="blue")
plot(IdxCorNumbers, xaxt="n", pch=19,col="blue", ylim=c(-1, 1), main="Chulwalar Capitlization Index", xlab = "", ylab="Correlation")
axis(1, labels = Names2, at=1:2, las=2, col="blue")
plot(InfCorNumbers, xaxt="n", pch=19,col="blue", ylim=c(-1, 1), main="Monthly Inflation Rate", xlab = "", ylab="Correlation")
axis(1, labels = Names2, at=1:2, las=2, col="blue")
plot(IndCorNumbers, xaxt="n", pch=19,col="blue", ylim=c(-1, 1), main="Proposed Spending for National Holidays", xlab = "", ylab="Correlation")
axis(1, labels = Names2, at=1:2, las=2, col="blue")
plot(IndCorNumbers2, xaxt="n", pch=19,col="blue",ylim=c(-1, 1), main="Influence of National Holiday", xlab = "", ylab="Correlation" )
axis(1, labels = Names2, at=1:2, las=2, col="blue")